### PR TITLE
Jupyter Notebook 2015 UX Survey

### PR DESCRIPTION
**Pull request by parente**
Survey tool CSV dump plus README capturing information about the survey runtime, marketing methods, and response data format.

### CODE REVIEW

**Comment by Carreau** [comment]
Thanks ! +1

**Comment by Carreau** [comment]
I've started to [look at it](https://github.com/Carreau/survey/blob/master/DataSurvey.ipynb), but not fluent in pandas.

500 response in < 1s, and 780 "Complete" forms.

**Comment by parente** [comment]
The ~500 in < 1s are partials where people did nothing other than click the link. The status=complete are going to be the most interesting.

**Comment by parente** [comment]
And if the start time = the completion time, it just means it's a partial. The README explains this: the tool doesn't know what to set the completion time to because, well, it was never completed. So it just sets both columns to the same value.

**Comment by parente** [comment]
I should have asked earlier: Is there anything else I'm missing that should go into this PR before merge or is it good to go? 

I'm holding off on posting anything to the Google Group for the moment about the close of the survey and availability of the data until this lands in case something needs to change.

**Comment by Carreau** [comment]
I was just waiting for +1 on someone else.
But then, merging.

**Comment by parente** [comment]
I was waiting for the +1 too. Didn't meant to rush. I was legitimately asking "did I miss anything, anybody?"

**Comment by ellisonbg** [comment]
+1 on the merge too!

On Mon, Jan 18, 2016 at 8:57 AM, Peter Parente <notifications@github.com>
wrote:

> I was waiting for the +1 too. Didn't meant to rush. I was legitimately
> asking "did I miss anything, anybody?"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/design/pull/22#issuecomment-172588550>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Note for next survey:

Ask with which language people use the notebook.

**Pull request merged**
