### PR TITLE
add community call logo

### PR DESCRIPTION
**Pull request by Zsailer**
This PR includes the logo I made for the monthly Jupyter Community Call.

I've been using this as the thumbnail for the YouTube videos. I wanted to share the logo here so we have a record of it and can adapt it for other purposes.

### CODE REVIEW

**Comment by Zsailer** [comment]
Here's a preview:

image

**Comment by Zsailer** [comment]
I made a few choices: 
* I used all lower-case to be consistent with "jupyter" in the main logo
* I adjusted the font weight to complement the main part of the logo (used regular).
* I used the second lightest grey (#757575) from the guidelines to complement the main logo.
* I moved the planet logo down slightly to balance the two-line text.

Pinging @tgeorgeux and @i-am-am for review.

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/edit-social-media-preview-images/1185/19

**Comment by choldgraf** [comment]
IMO, a challenge with the "powered by" logo is that the font size for "powered by" will be too small for many people to see. From an accessibility standpoint, I think there's value in letting the "jupyter" part of the logo lose a little bit of space specifically in the context of having a second word or phrase below the logo (we do the same thing in the Jupyter community forum ,see below), and I think any smaller font size for the "community forum" would be too small for many to see

image

**Comment by choldgraf** [comment]
Another possibility is to adopt the same pattern that NBViewer uses:

https://nbviewer.jupyter.org/

image

In this case, the jupyter logo itself is smaller, but it might a way to accomplish the same effect w/o breaking brand guidelines. WDYT @Zsailer?

**Comment by Zsailer** [comment]
@choldgraf I think that nbviewer logo *also* breaks the guidelines. The logo proportions break the rules on page 11. ☹️

**Comment by i-am-am** [comment]
We also can _change_ the guidelines if there's a good reason. It's just going to require thinking critically about why we need the change and what it should look like-- maybe a standard pattern for adding sub logos

**Comment by Zsailer** [comment]
@i-am-am Funny enough, I was totally trying to follow the brand guidelines and *accidently* ignored the rule on moving the logo 🤦‍♂ 

I'll rework this logo when I get a chance.

I sympathize with @choldgraf that using the "powered by" approach doesn't work here because the second line is too long.

**Comment by Zsailer** [comment]
@i-am-am also, thank you for the review. This is extremely helpful!

**Comment by Zsailer** [comment]
It would be nice to use the planet more flexibly. I think the [JupyterCon logo](https://blog.jupyter.org/jupytercon-2018-call-for-proposal-87986014ee0b) is nice, but I wanted to use the planet for the community call since it's broadly known+familiar across the community. Maybe our guidelines are too strict here? 

Though, I also fully acknowledge I'm not an expert on logo design and guidelines. Our designers (@i-am-am included) have thought a lot more about this stuff than I have. So I'm happy to adjust to what you think is best! 👍

**Comment by choldgraf** [comment]
I think a decent question for re-working some of the brand guidelines is to ask "is there a very common pattern that we're not allowing for in the guidelines?". I think that one missing-but-common pattern is "combining the Jupyter logo with text both above OR below the logo, in a form that is friendly for both small and large sizes".

Maybe it doesn't mean re-working pre-existing guidlines, but just adding some more for that particular use-case?
What do you two think?

**Comment by i-am-am** [comment]
Right, this reminds me of use cases like [mozilla's logo lockups](https://mozilla.design/expression) or the design for an updated IPython logo that the other interns and I worked on. We can give the community a way to use the planet and wordmark with other text. This is going to require some iterating to make it official, but if people have other examples of places it would get used or comments about what the important aspect are, it would be great to hear!

**Comment by choldgraf** [comment]
@i-am-am what would be a good place to iterate and give feedback for your team?

**Comment by choldgraf** [comment]
Hey all - just FYI I've updated the community forum logo to match the design guide, I think it still looks quite nice :-)

image

**Comment by i-am-am** [comment]
@choldgraf thank you for doing that!

For iterating and giving feedback, working in Figma is probably best. Free Figma accounts are limited, but seem to be less limited than what Figma lists as the limits-- any number of people can look at or edit documents. I'm starting a new job after this week, so this project will probably be passed off to @tgeorgeux or one of the other interns to help with.

**Comment by tgeorgeux** [comment]
Wow, just catching up on all of this now. Thanks @Zsailer for kicking this off and everybody for being involved. A couple of thoughts:

1) @choldgraf that looks great. Do you mind making a PR for that?
2) @Zsailer I think we can make the community call logo just like the one chris made for now.
3) I think we should re-visit the brand guidelines, and follow the ones we have in the meantime.
    - Specifically I think we should have a way to put the Jupyter Logo with additional text. I can even envision a template something like, Jupyter Community ____ with a balanced layout for that. We could also code a simple logo generator once we've got a good template, just thoughts.

**Comment by choldgraf** [comment]
> Specifically I think we should have a way to put the Jupyter Logo with additional text. I can even envision a template something like, Jupyter Community ____ with a balanced layout for that

yep I totally agree

**Comment by blink1073** [comment]
👍🏼

**Pull request merged**
