### PR TITLE
Analysis of UX survey results

### PR DESCRIPTION
**Pull request by parente**
@jtyberg and I have been chipping away at this analysis for a month now. It's reached steady-state. This PR has:

1. `report_dashboard.ipynb` which summarizes the results, can be viewed on nbviewer / github as a static report, and has interactive widgets / a dashboard layout if the reader wants to interact with the results. (Shortcut to the file in our branch to easy viewing on GitHub: https://github.com/ibm-et/design/blob/analysis/surveys/2015-notebook-ux/analysis/report_dashboard.ipynb)
2. The report can be run, viewed as a dashboard, interacted with in ~~binder~~ a tmpnb site: http://jupyter.cloudet.xyz/files/2015-notebook-ux-survey/analysis/deployed_dashboard/index.html. (Setting up binder instance was a bit harder because of the older image. Can tackle later.)
3. All of our prep notebooks are also included in this PR for reproducibility.

I've marked it a WIP for a few reasons:

1. I'd like to give it some time to bake here in case someone comes along and has some major feedback that we should address.
2. We're actually looking at improving the interactivity a bit more. (No ETA on this and it can come in another PR later.)
3. Maybe it doesn't belong here with the raw survey data since it includes our interpretation of the results. (Suggestions welcome for where else to put it if not here.)

Any and all feedback / comments welcome. (We can post back to the list about it before or after merging if that makes sense.)

/cc @fperez @ellisonbg

### CODE REVIEW

**Comment by parente** [comment]
I forgot the obligatory screenshot: running on Binder, using widgets, dashboard layout:

screen shot 2016-03-03 at 3 17 11 pm

**Comment by parente** [comment]
In prep for the dev meeting, @aluu317 and @peller created another version of the same UX survey report using the declarative widgets to provide more interactivity. It's now also in the PR (which I think needs some serious squashing at this point.)

I plan on working on the Binder updates to account for it. I'll also make sure it lives on jupyter.cloudet.xyz as a giant demo of dashboards, decl widgets, etc. for those that want to play with.

Before I do all the work against this repo / PR, it would be nice to address the question of whether the analysis notebooks, intermediate data, etc. should be merged here in jupyter/design alongside the raw data or not.

Any opinions?

New obligatory eyecandy screen cap:

ux-survey-decl

**Comment by rgbkrk** [comment]
> It would be nice to address the question of whether the analysis notebooks, intermediate data, etc. should be merged here in jupyter/design alongside the raw data or not.

I'd certainly like to see it in this repo, in context. Otherwise, a link to yet another repo seems fine.

**Comment by fperez** [comment]
I'm +1 on merging this here, I would only suggest having a *very short* REAMDE.md file that helps people who land on it on Github to orient themselves.  It can be as simple as:

* very short description of the directory, a couple of sentences.
* link to the binder/[cloudet](http://jupyter.cloudet.xyz/) deployment.
* link to the "entry point" notebook, so people know which one to start from.

No need to replicate in the README the great content that's in the included notebooks, it should really be a 5 minute job to have it in.  BTW, the top-level PR description already has 80% of that README :)

With that, I'd be happy merging.

**Comment by Carreau** [comment]
+1, I'm fine even merging that and iterating on subsequent PR if needed. Would that help you ?

**Comment by Carreau** [comment]
Any objection to give commit right to @parente for this repository ?

**Comment by parente** [comment]
> I'm +1 on merging this here, I would only suggest having a very short REAMDE.md file that helps people who land on it on Github to orient themselves. It can be as simple as:

Makes a lot of sense. Yes.

> +1, I'm fine even merging that and iterating on subsequent PR if needed. Would that help you ?

Working all in this PR is fine be me. Just wanted a sanity check before starting to point all the links in the notebook, binder, etc. to this repo if the decision was going to be "put it elsewhere."

Here's what I'd like to do to get to merge:

* [ ] README
* [ ] Adjust all links so they point here
* [ ] Make sure binder can build it
* [ ] Squash the commits a bit down some

At that point, if everyone else is +1, then by all means send it in. :+1:

**Comment by fperez** [comment]
Sounds like a good plan, go ahead with that and we can merge.

Delighted @parente commit rights here, if you think you'll be working often on this repo... If you think this is a one-off contribution, probably no need to. Just let us know!

**Comment by parente** [comment]
I doubt I'll be in here often. I'm cool with PR only for now. Thanks!

**Comment by parente** [comment]
Sounds like everyone was happy with merging this. Fire away!

**Pull request merged**
