### PR TITLE
add logo blue-print with dimensions

### PR DESCRIPTION
**Pull request by Carreau**
As for the [kilogram](http://en.wikipedia.org/wiki/Kilogram) It's nice to have a reference prototype, but it's better to have spec.

This fixes that by providing the actual center an radius of each circles in the logo. And yes they are circle if you are wondering. 
I use arbitrary Units anchored in the lower left, the one my inkscape canvas gave me. The unit where rounded to the closes pixel for the positions of the guide (which should move things by less than a 512th). 

Here is a scrennshot with a 512x512unit square as eye guide. 

capture d ecran 2014-12-13 a 18 39 48

Wondering if this makes  @rgbkrk not see chompy anymore. 

I'll tackle the gradient/color another day. 
Then we can try to make the logo with matplotlib.

### CODE REVIEW

**Comment by Carreau** [comment]
Various circles x,y and radius on a canvas of 1024x1024 with origin in the center of increasing coordinate bottom-> top ; left->right, as a json structure. 
```
[
  {
    "y": 0,
    "x": 0,
    "r": 406
  },
  {
    "y": -174,
    "x": 0,
    "r": 630
  },
  {
    "y": 174,
    "x": 0,
    "r": 630
  },
  {
    "y": 225,
    "x": -137,
    "r": 32
  },
  {
    "y": -181,
    "x": -169,
    "r": 20
  },
  {
    "y": -218,
    "x": 138,
    "r": 27
  }
]
```

**Comment by takluyver** [comment]
Was there a problem with this? I thought we were just being slow to merge it.

**Comment by Carreau** [comment]
Not particularly. That's design work, not particularly my field. The info is in the PR is enough.

**Comment by takluyver** [comment]
Reopening for now so we can evaluate this; I think having the SVG showing the proportions in the repo would be valuable.

**Comment by ellisonbg** [comment]
Yeah, I like this one...

**Comment by damianavila** [comment]
:+1: as well, to re-open it and have a reference like this one...

**Comment by takluyver** [comment]
OK, merging. If we want to tweak this, we can do so in further PRs.

**Pull request merged**
